const fs = require('fs');

let fileNames = [
    'mid', 'mid2', 'mid3', 'midSBxG', 'midSBxA',
    'fwd', 'fwd2', 'fwd3', 'fwdSBxG', 'fwdSBxA',
    'def', 'def2', 'def3', 'defSBxG', 'defSBxA'
];

fileNames.forEach((arrayElement) => {
    let fileName = 'c:\\EPLJava\\stat_tables\\' + arrayElement + '.html';

    console.log('Processing ' + fileName);

    fs.writeFileSync(fileName, translateUTFCode(fs.readFileSync(fileName, "utf8")), (err) => {
        if (err) console.log(err);
    });
});

function translateUTFCode(strVar){
   return(strVar.replace(/\\xc3\\x80/g, 'A')
                .replace(/\\xc3\\x81/g, 'A')
                .replace(/\\xc3\\x82/g, 'A')
                .replace(/\\xc3\\x83/g, 'A')
                .replace(/\\xc3\\x84/g, 'A')
                .replace(/\\xc3\\x85/g, 'A')
                .replace(/\\xc3\\x86/g, 'A')
                .replace(/\\xc3\\x87/g, 'C')
                .replace(/\\xc3\\x88/g, 'E')
                .replace(/\\xc3\\x89/g, 'E')
                .replace(/\\xc3\\x8a/g, 'E')
                .replace(/\\xc3\\x8b/g, 'E')
                .replace(/\\xc3\\x8c/g, 'I')
                .replace(/\\xc3\\x8d/g, 'I')
                .replace(/\\xc3\\x8e/g, 'I')
                .replace(/\\xc3\\x8f/g, 'I')
                .replace(/\\xc3\\x92/g, 'O')
                .replace(/\\xc3\\x93/g, 'O')
                .replace(/\\xc3\\x94/g, 'O')
                .replace(/\\xc3\\x95/g, 'O')
                .replace(/\\xc3\\x96/g, 'O')
                .replace(/\\xc3\\x98/g, 'O')
                .replace(/\\xc3\\x99/g, 'U')
                .replace(/\\xc3\\x9a/g, 'U')
                .replace(/\\xc3\\x9b/g, 'U')
                .replace(/\\xc3\\x9c/g, 'U')
                .replace(/\\xc3\\x9d/g, 'Y')
                .replace(/\\xc3\\xa0/g, 'a')
                .replace(/\\xc3\\xa1/g, 'a')
                .replace(/\\xc3\\xa2/g, 'a')
                .replace(/\\xc3\\xa3/g, 'a')
                .replace(/\\xc3\\xa4/g, 'a')
                .replace(/\\xc3\\xa5/g, 'a')
                .replace(/\\xc3\\xa6/g, 'a')
                .replace(/\\xc3\\xa7/g, 'c')
                .replace(/\\xc3\\xa8/g, 'e')
                .replace(/\\xc3\\xa9/g, 'e')
                .replace(/\\xc3\\xaa/g, 'e')
                .replace(/\\xc3\\xab/g, 'e')
                .replace(/\\xc3\\xac/g, 'i')
                .replace(/\\xc3\\xad/g, 'i')
                .replace(/\\xc3\\xae/g, 'i')
                .replace(/\\xc3\\xaf/g, 'i')
                .replace(/\\xc3\\xb1/g, 'n')
                .replace(/\\xc3\\xb2/g, 'o')
                .replace(/\\xc3\\xb3/g, 'o')
                .replace(/\\xc3\\xb4/g, 'o')
                .replace(/\\xc3\\xb5/g, 'o')
                .replace(/\\xc3\\xb6/g, 'o')
                .replace(/\\xc3\\xb8/g, 'o')
                .replace(/\\xc3\\xb9/g, 'u')
                .replace(/\\xc3\\xba/g, 'u')
                .replace(/\\xc3\\xbb/g, 'u')
                .replace(/\\xc3\\xbc/g, 'u')
                .replace(/\\xc3\\xbd/g, 'y')
                .replace(/\\xc3\\xbf/g, 'y')
                .replace(/\\xc4\\x80/g, 'A')
                .replace(/\\xc4\\x81/g, 'a')
                .replace(/\\xc4\\x82/g, 'A')
                .replace(/\\xc4\\x83/g, 'a')
                .replace(/\\xc4\\x84/g, 'A')
                .replace(/\\xc4\\x85/g, 'a')
                .replace(/\\xc4\\x86/g, 'C')
                .replace(/\\xc4\\x87/g, 'c')
                .replace(/\\xc4\\x88/g, 'C')
                .replace(/\\xc4\\x89/g, 'c')
                .replace(/\\xc4\\x8a/g, 'C')
                .replace(/\\xc4\\x8b/g, 'c')
                .replace(/\\xc4\\x8c/g, 'C')
                .replace(/\\xc4\\x8d/g, 'c')
                .replace(/\\xc4\\x8e/g, 'D')
                .replace(/\\xc4\\x8f/g, 'd')
                .replace(/\\xc4\\x90/g, 'D')
                .replace(/\\xc4\\x91/g, 'd')
                .replace(/\\xc4\\x92/g, 'E')
                .replace(/\\xc4\\x93/g, 'E')
                .replace(/\\xc4\\x94/g, 'E')
                .replace(/\\xc4\\x95/g, 'E')
                .replace(/\\xc4\\x96/g, 'E')
                .replace(/\\xc4\\x97/g, 'E')
                .replace(/\\xc4\\x98/g, 'E')
                .replace(/\\xc4\\x99/g, 'E')
                .replace(/\\xc4\\x9a/g, 'E')
                .replace(/\\xc4\\x9b/g, 'E')
                .replace(/\\xc4\\x9c/g, 'G')
                .replace(/\\xc4\\x9d/g, 'g')
                .replace(/\\xc4\\x9e/g, 'G')
                .replace(/\\xc4\\x9f/g, 'g')
                .replace(/\\xc4\\xa0/g, 'G')
                .replace(/\\xc4\\xa1/g, 'g')
                .replace(/\\xc4\\xa2/g, 'G')
                .replace(/\\xc4\\xa3/g, 'g')
                .replace(/\\xc4\\xa4/g, 'H')
                .replace(/\\xc4\\xa5/g, 'h')
                .replace(/\\xc4\\xa6/g, 'H')
                .replace(/\\xc4\\xa7/g, 'h')
                .replace(/\\xc4\\xa8/g, 'I')
                .replace(/\\xc4\\xa9/g, 'i')
                .replace(/\\xc4\\xaa/g, 'I')
                .replace(/\\xc4\\xab/g, 'i')
                .replace(/\\xc4\\xac/g, 'I')
                .replace(/\\xc4\\xad/g, 'i')
                .replace(/\\xc4\\xae/g, 'I')
                .replace(/\\xc4\\xaf/g, 'i')
                .replace(/\\xc4\\xb0/g, 'I')
                .replace(/\\xc4\\xb1/g, 'i')
                .replace(/\\xc4\\xb4/g, 'J')
                .replace(/\\xc4\\xb5/g, 'j')
                .replace(/\\xc4\\xb9/g, 'L')
                .replace(/\\xc4\\xba/g, 'l')
                .replace(/\\xc4\\xbb/g, 'L')
                .replace(/\\xc4\\xbc/g, 'l')
                .replace(/\\xc4\\xbd/g, 'L')
                .replace(/\\xc4\\xbe/g, 'l')
                .replace(/\\xc4\\xbf/g, 'L')
                .replace(/\\xc5\\x80/g, 'l')
                .replace(/\\xc5\\x81/g, 'L')
                .replace(/\\xc5\\x82/g, 'l')
                .replace(/\\xc5\\x83/g, 'N')
                .replace(/\\xc5\\x84/g, 'n')
                .replace(/\\xc5\\x85/g, 'N')
                .replace(/\\xc5\\x86/g, 'n')
                .replace(/\\xc5\\x87/g, 'N')
                .replace(/\\xc5\\x88/g, 'n')
                .replace(/\\xc5\\x8a/g, 'N')
                .replace(/\\xc5\\x8b/g, 'n')
                .replace(/\\xc5\\x8c/g, 'O')
                .replace(/\\xc5\\x8d/g, 'o')
                .replace(/\\xc5\\x8e/g, 'O')
                .replace(/\\xc5\\x8f/g, 'o')
                .replace(/\\xc5\\x90/g, 'O')
                .replace(/\\xc5\\x91/g, 'o')
                .replace(/\\xc5\\x9a/g, 'S')
                .replace(/\\xc5\\x9b/g, 's')
                .replace(/\\xc5\\x9c/g, 'S')
                .replace(/\\xc5\\x9d/g, 's')
                .replace(/\\xc5\\x9e/g, 'S')
                .replace(/\\xc5\\x9f/g, 's')
                .replace(/\\xc5\\xa0/g, 'S')
                .replace(/\\xc5\\xa1/g, 's')
                .replace(/\\xc5\\xa8/g, 'U')
                .replace(/\\xc5\\xa9/g, 'u')
                .replace(/\\xc5\\xaa/g, 'U')
                .replace(/\\xc5\\xab/g, 'u')
                .replace(/\\xc5\\xac/g, 'U')
                .replace(/\\xc5\\xad/g, 'u')
                .replace(/\\xc5\\xae/g, 'U')
                .replace(/\\xc5\\xaf/g, 'u')
                .replace(/\\xc5\\xb0/g, 'U')
                .replace(/\\xc5\\xb1/g, 'u')
                .replace(/\\xc5\\xb2/g, 'U')
                .replace(/\\xc5\\xb3/g, 'u')
                .replace(/\\xc5\\xb9/g, 'Z')
                .replace(/\\xc5\\xba/g, 'z')
                .replace(/\\xc5\\xbb/g, 'Z')
                .replace(/\\xc5\\xbc/g, 'z')
                .replace(/\\xc5\\xbd/g, 'Z')
                .replace(/\\xc5\\xbe/g, 'z')
                .replace(/\\'/g, '\'')
                .replace(/ß/g, 'ss')
                );
}